/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiPublicResetPasswordRouteImport } from './routes/api/public/reset-password'
import { Route as ApiPublicLogRouteImport } from './routes/api/public/log'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicAlertRouteImport } from './routes/api/public/alert'
import { Route as AuthenticatedDevicesDeviceIdRouteImport } from './routes/_authenticated/devices.$deviceId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicResetPasswordRoute = ApiPublicResetPasswordRouteImport.update({
  id: '/api/public/reset-password',
  path: '/api/public/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogRoute = ApiPublicLogRouteImport.update({
  id: '/api/public/log',
  path: '/api/public/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertRoute = ApiPublicAlertRouteImport.update({
  id: '/api/public/alert',
  path: '/api/public/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevicesDeviceIdRoute =
  AuthenticatedDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => AuthenticatedDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot': typeof ForgotRoute
  '/reset': typeof ResetRoute
  '/verify': typeof VerifyRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdRoute
  '/api/public/alert': typeof ApiPublicAlertRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/log': typeof ApiPublicLogRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot': typeof ForgotRoute
  '/reset': typeof ResetRoute
  '/verify': typeof VerifyRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdRoute
  '/api/public/alert': typeof ApiPublicAlertRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/log': typeof ApiPublicLogRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot': typeof ForgotRoute
  '/reset': typeof ResetRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdRoute
  '/api/public/alert': typeof ApiPublicAlertRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/log': typeof ApiPublicLogRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot'
    | '/reset'
    | '/verify'
    | '/alerts'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/settings'
    | '/devices/$deviceId'
    | '/api/public/alert'
    | '/api/public/ingest'
    | '/api/public/log'
    | '/api/public/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot'
    | '/reset'
    | '/verify'
    | '/alerts'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/settings'
    | '/devices/$deviceId'
    | '/api/public/alert'
    | '/api/public/ingest'
    | '/api/public/log'
    | '/api/public/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot'
    | '/reset'
    | '/verify'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/logs'
    | '/_authenticated/settings'
    | '/_authenticated/devices/$deviceId'
    | '/api/public/alert'
    | '/api/public/ingest'
    | '/api/public/log'
    | '/api/public/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotRoute: typeof ForgotRoute
  ResetRoute: typeof ResetRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicAlertRoute: typeof ApiPublicAlertRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicLogRoute: typeof ApiPublicLogRoute
  ApiPublicResetPasswordRoute: typeof ApiPublicResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/reset-password': {
      id: '/api/public/reset-password'
      path: '/api/public/reset-password'
      fullPath: '/api/public/reset-password'
      preLoaderRoute: typeof ApiPublicResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log': {
      id: '/api/public/log'
      path: '/api/public/log'
      fullPath: '/api/public/log'
      preLoaderRoute: typeof ApiPublicLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alert': {
      id: '/api/public/alert'
      path: '/api/public/alert'
      fullPath: '/api/public/alert'
      preLoaderRoute: typeof ApiPublicAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/devices/$deviceId': {
      id: '/_authenticated/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AuthenticatedDevicesDeviceIdRouteImport
      parentRoute: typeof AuthenticatedDevicesRoute
    }
  }
}

interface AuthenticatedDevicesRouteChildren {
  AuthenticatedDevicesDeviceIdRoute: typeof AuthenticatedDevicesDeviceIdRoute
}

const AuthenticatedDevicesRouteChildren: AuthenticatedDevicesRouteChildren = {
  AuthenticatedDevicesDeviceIdRoute: AuthenticatedDevicesDeviceIdRoute,
}

const AuthenticatedDevicesRouteWithChildren =
  AuthenticatedDevicesRoute._addFileChildren(AuthenticatedDevicesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRouteWithChildren
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRouteWithChildren,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotRoute: ForgotRoute,
  ResetRoute: ResetRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicAlertRoute: ApiPublicAlertRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicLogRoute: ApiPublicLogRoute,
  ApiPublicResetPasswordRoute: ApiPublicResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
